options:
  version:
    type: string
    default: "v1.0.6"
    description: |
        The version of Kubernetes to use in this charm.  The version is
        inserted in the configuration files that specify the hyperkube
        container to use when starting a Kubernetes cluster.  Changing this
        value will restart the Kubernetes cluster.
  ca:
    type: string
    default: ""
    description: |
        The Certificate Authority for this Kubernetes cluster. The default of
        none will generate a self signed Certficate Authroity. This will be used
        to generate cerificates and keys for the cluster.
  cidr:
    type: string
    default: 10.1.0.0/16
    description: |
      Network CIDR to assign to K8s service groups
